version: '3.7'

# Run with UID=$(id -u) GID=$(id -g) docker-compose up
services:
  mysql_osticket:
    container_name: mysql_osticket
    user: $CURRENT_USER
    restart: unless-stopped
    image: mysql:5.7.35
    env_file: ./env
    volumes:
      -  data_osticket_mysql:/var/lib/mysql
    ports:
      - 3306:3306

#  postfix:
#    image: juanluisbaptiste/postfix:latest
#    expose:
#      - "25"
#    env_file:
#      - env/.envpostfix
#    volumes:
#     - "/etc/localtime:/etc/localtime:ro"
#    networks:
#      - basnet
      
  osticket:
    container_name: sbdi_osticket
#    user: $CURRENT_USER
    restart: unless-stopped
    image: ghcr.io/biodiversitydata-se/docker-osticket/osticket:1.15.4
#    build:
#      context: .
#      dockerfile: Dockerfile
    depends_on:
      - mysql_osticket
    links: 
      - mysql_osticket:mysql
    env_file: ./env
    volumes:
      - data_osticket_osticket:/var/www/html
    ports:
    - 8080:80

volumes:
  data_osticket_mysql:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "./.root/var/lib/mysql"
  data_osticket_osticket:
    driver: local
    driver_opts:
      type: none
      o: "bind"
      device: "./.root/var/www/html"
      
      