version: '3.7'
services:
  mysql_osticket:
    container_name: mysql_osticket
    restart: unless-stopped
    image: mysql:5.7.35
    env_file: ./env/.envosticket
    volumes:
      -  data_osticket_mysql:/var/lib/mysql
      
  osticket:
    container_name: sbdi_osticket
    image: bioatlas/osticket:1.15.4    
    restart: unless-stopped
    depends_on:
      - mysql_osticket
    links: 
      - mysql_osticket:mysql
    env_file: ./env/.envosticket
    volumes:
      - data_osticket_osticket:/var/lib/osticket
    ports:
      - 80:80
  
volumes:
  data_osticket_mysql:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${DOCKER_VOLUMES:-/mnt/data/volumes}/osticket_mysql"
  data_osticket_osticket:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${DOCKER_VOLUMES:-/mnt/data/volumes}/osticket_osticket"

  
