name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

        # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Read Tag File
        id: tagfile
        uses: juliangruber/read-file-action@v1
        with: 
          path: ./tags
        
      - name: Set Environment Variables
        run: |
          IMG=osticket
          echo "IMG=${IMG}" >> $GITHUB_ENV
          echo "IMAGE=ghcr.io/${GITHUB_REPOSITORY}/${IMG}" >> $GITHUB_ENV
          echo "IMAGE_VERSION=$(echo ${{ steps.tagfile.outputs.content }} | tail -1)" >> $GITHUB_ENV
          

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      
      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: .
          # Note: tags has to be all lower-case
          tags: |
            #ghcr.io/biodiversitydata-se/docker-osticket/osticket:latest
            #${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{env.IMAGE_VERSION}}
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/master' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
