name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
        
  #  - name: Login to Docker Hub
  #    uses: docker/login-action@v1
  #    env:
  #      DOCKER_USER: ${{secrets.DOCKERHUB_USER}}
  #      DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
        
    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Build image and push
      uses: docker/build-push-action@v2
      with:
        context: ./
        tags: |
          biodiversitydata-se/docker-osticket:latest
        push: ${{ github.ref == 'refs/heads/main' }}
      
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
